from input_generators import *

REGION_SIZE_N = 3
COLUMN_SIZE = 8

STEPS_NUMBER = 100011

GENERATOR = Cross

INITIAL_PERMANENCE = 0.28
SYNAPSE_THRESHOLD = 0.25
DENDRITE_PERMANENCE_INC_DELTA = 0.005
DENDRITE_PERMANENCE_DEC_DELTA = -0.007

PASSIVE_TIME_TO_ACTIVE_THRESHOLD = 100




