from input_generators import *

REGION_SIZE_N = 3
COLUMN_SIZE = 6

STEPS_NUMBER = 5111

# GENERATOR = Cross
GENERATOR = ConstantActiveBit

INITIAL_PERMANENCE = 0.28
SYNAPSE_THRESHOLD = 0.25
DENDRITE_PERMANENCE_INC_DELTA = 0.005
DENDRITE_PERMANENCE_DEC_DELTA = -0.007

PASSIVE_TIME_TO_ACTIVE_THRESHOLD = 1440




