from input_generators import *

REGION_SIZE_N = 3
COLUMN_SIZE = 3

STEPS_NUMBER = 5000

GENERATOR = HardSteps
# GENERATOR = ConstantActiveBit

INITIAL_PERMANENCE = 0.50
SYNAPSE_THRESHOLD = 0.25
DENDRITE_PERMANENCE_INC_DELTA = 0.02
DENDRITE_PERMANENCE_DEC_DELTA = -0.1

PASSIVE_TIME_TO_ACTIVE_THRESHOLD = 2000




